name: Build docker

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v2
            
            - name: Setup docker
              uses: docker/setup-buildx-action@v2

            - name: Build Docker
              run: |
                docker login --username erixfrentoni --password ${{secrets.GHR_TOKEN}} ghcr.io
                docker build -t ghcr.io/erixfrentoni/testapp:latest .
                docker push ghcr.io/erixfrentoni/testapp:latest  


