name: Build docker

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v2

            - name: login
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: erixfrentoni
                password: ${{secrets.GHR_TOKEN}}
            

            - name: Setup docker
              uses: docker/setup-buildx-action@v2

            - name: Build Docker
              run: |
                docker build -t ghcr.io/erixfrentoni/testapp:latest .  

            - name: Push Dimg
              run: |
                docker push ghcr.io/erixfrentoni/testapp:latest
